USE ORDERFORM;

CREATE TABLE ORDERLINE(
	LineId INT NOT NULL,
	OrderNumber INT NOT NULL REFERENCES FORM(OrderNumber),
    ProductNumber VARCHAR(50) NOT NULL REFERENCES PRODUCT(ProductNumber),
    Quantity INT NOT NULL
);